<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Practitioner Invoice {{ $invoice->invoice_number ?? '#' . $invoice->id }}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .email-container {
            background-color: #ffffff;
            border-radius: 8px;
            padding: 40px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .header {
            border-bottom: 3px solid #3b82f6;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .organization-name {
            font-size: 28px;
            font-weight: bold;
            color: #1e40af;
            margin: 0 0 10px 0;
        }
        .invoice-title {
            font-size: 24px;
            font-weight: bold;
            color: #374151;
            margin: 20px 0 10px 0;
        }
        .invoice-number {
            font-size: 18px;
            color: #6b7280;
        }
        .message {
            background-color: #eff6ff;
            border-left: 4px solid #3b82f6;
            padding: 15px 20px;
            margin: 20px 0;
            border-radius: 4px;
        }
        .success-message {
            background-color: #f0fdf4;
            border-left: 4px solid #22c55e;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 30px 0;
        }
        thead {
            background-color: #f3f4f6;
        }
        th {
            text-align: left;
            padding: 12px;
            font-weight: 600;
            color: #374151;
            border-bottom: 2px solid #e5e7eb;
        }
        th.text-right {
            text-align: right;
        }
        td {
            padding: 12px;
            border-bottom: 1px solid #e5e7eb;
            color: #374151;
        }
        td.text-right {
            text-align: right;
        }
        .totals-section {
            margin-top: 20px;
            display: flex;
            justify-content: flex-end;
        }
        .totals-table {
            width: 300px;
        }
        .totals-table tr td {
            padding: 8px 12px;
            border: none;
        }
        .totals-table tr.total td {
            font-weight: bold;
            font-size: 18px;
            border-top: 2px solid #e5e7eb;
            padding-top: 15px;
        }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            color: #6b7280;
            font-size: 14px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="email-container">
        <div class="header">
            <div class="organization-name">{{ $organization['name'] ?? 'Practice' }}</div>
        </div>

        @if($recipientType === 'tenant')
            <h1 class="invoice-title">New Practitioner Invoice</h1>
            <p class="invoice-number">Invoice #{{ $invoice->invoice_number ?? $invoice->id }}</p>
            
            <div class="message">
                <p style="margin: 0; font-weight: 600; color: #1e40af;">
                    A new invoice has been generated by a practitioner and requires your attention.
                </p>
            </div>

            <p>Dear {{ $organization['name'] ?? 'Practice' }},</p>
            <p>A practitioner has generated an invoice for their professional services. Please review the details below:</p>
        @else
            <h1 class="invoice-title">Invoice Generated Successfully</h1>
            <p class="invoice-number">Invoice #{{ $invoice->invoice_number ?? $invoice->id }}</p>
            
            <div class="message success-message">
                <p style="margin: 0; font-weight: 600; color: #15803d;">
                    Your invoice has been generated successfully and sent to the clinic.
                </p>
            </div>

            <p>Dear {{ $recipient['name'] ?? 'Practitioner' }},</p>
            <p>Your invoice has been successfully generated and sent to the clinic for processing. Details are below:</p>
        @endif

        <table>
            <thead>
                <tr>
                    <th>Description</th>
                    <th class="text-right">Amount</th>
                </tr>
            </thead>
            <tbody>
                @if(isset($invoiceData['lines']) && is_array($invoiceData['lines']))
                    @foreach($invoiceData['lines'] as $line)
                        <tr>
                            <td>{{ $line['desc'] ?? 'Professional Services' }}</td>
                            <td class="text-right">${{ number_format($line['line_subtotal'] ?? $line['unit_price'] ?? 0, 2) }}</td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <td>Professional Services</td>
                        <td class="text-right">${{ number_format($invoice->price, 2) }}</td>
                    </tr>
                @endif
            </tbody>
        </table>

        <div class="totals-section">
            <table class="totals-table">
                <tr>
                    <td>Subtotal:</td>
                    <td class="text-right">${{ number_format($invoice->subtotal ?? $invoice->price, 2) }}</td>
                </tr>
                @if($invoice->tax_total > 0)
                    <tr>
                        <td>Tax:</td>
                        <td class="text-right">${{ number_format($invoice->tax_total, 2) }}</td>
                    </tr>
                @endif
                <tr class="total">
                    <td>Total:</td>
                    <td class="text-right">${{ number_format($invoice->price, 2) }}</td>
                </tr>
            </table>
        </div>

        @if($recipientType === 'tenant')
            <p style="margin-top: 30px;">
                <strong>Next Steps:</strong><br>
                Please review this invoice and process payment according to your standard procedures.
            </p>
        @else
            <p style="margin-top: 30px;">
                <strong>Status:</strong> Pending<br>
                The clinic has been notified and will process your payment according to their standard procedures.
            </p>
        @endif

        <div class="footer">
            <p style="margin: 0;">This is an automated notification from {{ $organization['name'] ?? 'Practice' }}.</p>
            @if(!empty($organization['email']))
                <p style="margin: 5px 0 0 0; color: #6b7280;">{{ $organization['email'] }}</p>
            @endif
            @if(!empty($organization['phone']))
                <p style="margin: 5px 0 0 0; color: #6b7280;">{{ $organization['phone'] }}</p>
            @endif
        </div>
    </div>
</body>
</html>

