<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Appointment Summary</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background-color: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .appointment-details {
            background-color: #e3f2fd;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .summary-content {
            background-color: #f5f5f5;
            padding: 20px;
            border-radius: 8px;
            border-left: 4px solid #2196f3;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 12px;
            color: #666;
        }
        h1 {
            color: #2196f3;
            margin-top: 0;
        }
        h2 {
            color: #1976d2;
            margin-top: 0;
        }
        .detail-row {
            margin-bottom: 8px;
        }
        .detail-label {
            font-weight: bold;
            color: #555;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Your Appointment Summary</h1>
        <p>Hello {{ $patient_name }},</p>
        <p>Here is your appointment summary generated by our AI assistant based on your recent session.</p>
    </div>

    <div class="appointment-details">
        <h2>Appointment Details</h2>
        <div class="detail-row">
            <span class="detail-label">Date & Time:</span> {{ $appointment_date }}
        </div>
        <div class="detail-row">
            <span class="detail-label">Service:</span> {{ $service_name }}
        </div>
        <div class="detail-row">
            <span class="detail-label">Provider:</span> {{ $practitioner_names }}
        </div>
    </div>

    <div class="summary-content">
        <h2>AI-Generated Session Summary</h2>
        <div style="white-space: pre-line;">{{ $ai_summary }}</div>
    </div>

    <div class="footer">
        <p><strong>Please note:</strong> This summary has been generated by artificial intelligence based on your session data. While we strive for accuracy, please contact your healthcare provider if you have any questions or concerns about the information provided.</p>
        
        <p>This summary is for your personal records. Please keep it secure and do not share it with unauthorized individuals.</p>
        
        <p>If you have any questions about your care or this summary, please don't hesitate to contact us.</p>
        
        <p>Best regards,<br>
        <strong>{{ $organization_name }}</strong></p>
    </div>
</body>
</html>