<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Invoices Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        h1 {
            text-align: center;
            color: #2563eb;
            margin-bottom: 20px;
        }
        .meta {
            text-align: center;
            margin-bottom: 20px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th {
            background-color: #f3f4f6;
            padding: 10px;
            text-align: left;
            border: 1px solid #d1d5db;
            font-weight: bold;
        }
        td {
            padding: 8px;
            border: 1px solid #e5e7eb;
        }
        tbody tr:nth-child(even):not(:last-child) {
            background-color: #f9fafb;
        }
        .text-right {
            text-align: right;
        }
        .status-badge {
            padding: 2px 8px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: bold;
        }
        .status-paid {
            background-color: #d1fae5;
            color: #065f46;
        }
        .status-pending {
            background-color: #fef3c7;
            color: #92400e;
        }
        .status-partial {
            background-color: #dbeafe;
            color: #1e40af;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #9ca3af;
        }
    </style>
</head>
<body>
    <h1>Invoices Export</h1>
    <div class="meta">
        <p>Generated on: {{ now()->format('F d, Y H:i:s') }}</p>
        <p>Total Invoices: {{ count($invoices) }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Invoice #</th>
                <th>Type</th>
                <th>Status</th>
                <th>Payment Method</th>
                <th>Due Date</th>
                <th>Created At</th>
                <th class="text-right">Subtotal</th>
                <th class="text-right">Tax</th>
                <th class="text-right">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach($invoices as $invoice)
            <tr>
                <td>{{ $invoice->invoice_number ?: '#' . $invoice->id }}</td>
                <td>{{ ucfirst($invoice->invoiceable_type) }}</td>
                <td>
                    <span class="status-badge status-{{ $invoice->status ?? 'pending' }}">
                        {{ strtoupper($invoice->status ?? 'pending') }}
                    </span>
                </td>
                <td>{{ $invoice->payment_method ?? 'N/A' }}</td>
                <td>{{ $invoice->due_date ? $invoice->due_date->format('Y-m-d') : 'N/A' }}</td>
                <td>{{ $invoice->created_at->format('Y-m-d') }}</td>
                <td class="text-right">{{ $currency }} {{ number_format($invoice->subtotal, 2) }}</td>
                <td class="text-right">{{ $currency }} {{ number_format($invoice->tax_total, 2) }}</td>
                <td class="text-right"><strong>{{ $currency }} {{ number_format($invoice->price, 2) }}</strong></td>
            </tr>
            @endforeach
            <!-- Totals Row at the end of tbody to ensure it renders last -->
            <tr style="background-color: #e5e7eb; font-weight: bold; border-top: 2px solid #374151;">
                <td colspan="6" style="text-align: left; padding: 12px 8px; font-size: 13px;"><strong>TOTALS</strong></td>
                <td class="text-right" style="padding: 12px 8px; font-size: 13px;"><strong>{{ $currency }} {{ number_format($invoices->sum('subtotal'), 2) }}</strong></td>
                <td class="text-right" style="padding: 12px 8px; font-size: 13px;"><strong>{{ $currency }} {{ number_format($invoices->sum('tax_total'), 2) }}</strong></td>
                <td class="text-right" style="padding: 12px 8px; font-size: 13px;"><strong>{{ $currency }} {{ number_format($invoices->sum('price'), 2) }}</strong></td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        <p>This document was automatically generated by the system.</p>
    </div>
</body>
</html>

